name: Build and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    timeout-minutes: 15
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 26
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build, test and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -Pcoverage org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: openapi-spec
          path: target/openapi.json
          if-no-files-found: warn

      - uses: nais/docker-build-push@f8bc7437f7549c2b08197152d781b98f8727a08a # v0
        if: github.event_name == 'push'
        id: docker-build-push
        with:
          team: oksty
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}

  # deploy-prod:
  #   needs: [build, deploy-dev]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  #     - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
  #       env:
  #         CLUSTER: prod-gcp
  #         RESOURCE: .nais/app-prod.yaml
  #         VAR: image=${{ needs.build.outputs.image }}
